const dataPorts = [
	{
		id: 1,
		name: "Santos Port",
		category: "filter-santos",
		image: "assets/img/port/santosphoto.jpg",
		link: "https://www.portodesantos.com.br",
		video: "kNT0KaooDYw",
	},
	{
		id: 2,
		name: "Paranagua Port",
		category: "filter-paranagua",
		image: "assets/img/port/png.jpg",
		link: "https://www.portosdoparana.pr.gov.br/",
		video: "jgrl9oKIF9I",
	},
	{
		id: 3,
		name: "Imbituba Port",
		category: "filter-imbituba",
		image: "assets/img/port/ibb.jpg",
		link: "https://portodeimbituba.com.br/",
		video: "SUL1nUoIFiQ",
	},
	{
		id: 4,
		name: "Rio de Janeiro Port",
		category: "filter-rio",
		image: "assets/img/port/rio.jpg",
		link: "https://www.portosrio.gov.br/",
		video: "BOPpMa20WOQ",
	},
	{
		id: 5,
		name: "Vitoria Port",
		category: "filter-vitoria",
		image: "assets/img/port/vix.jpg",
		link: "http://www.portodevitoria.com.br/",
		video: "JBYqwhcqSeA",
	},
	{
		id: 6,
		name: "Salvador Port",
		category: "filter-salvador",
		image: "assets/img/port/salvador.jpg",
		link: "https://www.codeba.gov.br/eficiente/sites/portalcodeba/pt-br/home.php",
		video: "5eIDp0sZi_4",
	},
	{
		id: 7,
		name: "Itaqui Port",
		category: "filter-itaqui",
		image: "assets/img/port/itaq.jpg",
		link: "https://www.portodoitaqui.com",
		video: "j9dIbuLVTII",
	},
	{
		id: 8,
		name: "Sao Francisco do Sul Port",
		category: "filter-saochico",
		image: "assets/img/port/sfs.jpeg",
		link: "https://www.portosaofrancisco.com.br/",
		video: "EFTn5TarOaU",
	},
	{
		id: 9,
		name: "Rio Grande Port",
		category: "filter-riogrande",
		image: "assets/img/port/rg.jpg",
		link: "https://www.portosrs.com.br/site/",
		video: "YEmxatrKBUo",
	},
	{
		id: 10,
		name: "Barcarena Port",
		category: "filter-santarem",
		image: "assets/img/port/conde.JPG",
		link: "https://www.cdp.com.br/porto-de-vila-do-conde/",
		video: "UITdVaoaLtU",
	},
	{
		id: 11,
		name: "Pecem Port",
		category: "filter-pecem",
		image: "assets/img/port/pcm.jpg",
		link: "https://www.complexodopecem.com.br/",
		video: "YvQ9bqC2x_w",
	},
	{
		id: 12,
		name: "Itajai Port",
		category: "filter-itajai",
		image: "assets/img/port/itj.jpg",
		link: "https://www.portoitajai.com.br/",
		video: "1bR8EPGS1_I",
	},
	{
		id: 13,
		name: "Navegantes Port",
		category: "filter-navegantes",
		image: "assets/img/port/nvtsc.jpg",
		link: "https://www.portonave.com.br/en/",
		video: "rdK84IifR08",
	},
	{
		id: 14,
		name: "Belem Port",
		category: "filter-belem",
		image: "assets/img/port/bl.JPG",
		link: "https://www.cdp.com.br/porto-de-belem/",
		video: "UITdVaoaLtU",
	},
];

export default dataPorts;
